server: &server
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *server
  database: magmazine

test: &test
  <<: *server
  database: magmazine_test

production:
  <<: *server
  database: magmazine

cucumber:
  <<: *test
